### ISSUE TITLE
http_proxy issue running dapper behind firewall

### ISSUE THREAD

**Issue by scheetz** [rancher/dapper#22]
Step 8 : RUN apt-get update && apt-get install -y python-pip
 ---> Running in 42a7d9450794
Get:1 http://httpredir.debian.org jessie InRelease [8127 B]
Get:2 http://httpredir.debian.org jessie-updates InRelease [8127 B]
Get:3 http://security.debian.org jessie/updates InRelease [8127 B]
Splitting up /var/lib/apt/lists/partial/httpredir.debian.org_debian_dists_jessie_InRelease into data and signature failedIgn http://httpredir.debian.org jessie InRelease
E: GPG error: http://httpredir.debian.org jessie InRelease: Clearsigned file isn't valid, got 'NODATA' (does the network require authentication?)
The command '/bin/sh -c apt-get update && apt-get install -y python-pip' returned a non-zero code: 100

**Comment by imikushin** [comment]
@scheetz How do you normally build docker images behind a firewall? Particularly when the Dockerfile does **not** use `http_proxy` environment variable.

**Comment by scheetz** [comment]
Using `docker build --build-arg=http_proxy=mycorp.com .`  Looks like you figured it out already, thanks.
