### ISSUE TITLE
Support newer Docker API versions

### ISSUE THREAD

**Issue by LLParse** [rancher/dapper#45]
Could we please update the shipped Docker binaries? This tool is unusable on modern Docker releases.

`Error response from daemon: client version 1.21 is too old. Minimum supported API version is 1.24, please upgrade your client to a newer version`

```
Server:
 Version:      17.03.2-ee-5
 API version:  1.27 (minimum version 1.24)
 Go version:   go1.7.5
 Git commit:   fa09039
 Built:        Wed Jul 19 23:56:45 2017
 OS/Arch:      windows/amd64
 Experimental: false
```

**Comment by Shuliyey** [comment]
shouldn't this be related to the docker client version?

**Comment by ibuildthecloud** [comment]
Master has been updated to latest version of go, docker, etc.
