### ISSUE TITLE
https://releases.rancher.com/dapper/latest/dapper-Darwin-x86_64 fails with Segmentation Fault

### ISSUE THREAD

**Issue by bjfr** [rancher/dapper#47]
**RancherOS Version: (ros os version)**
Tested with  1.1.0 and 1.0.3

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
The problem is building the ISO, not running it

On the latest recent release of Mac OSX High Sierra v10.13.1, the dapper executable located at 

https://releases.rancher.com/dapper/latest/dapper-Darwin-x86_64

fails with a segmentation fault 11.

If you build dapper yourself using **go version go1.9.2 darwin/amd64** and modify *Makefile* to use the local version the build seems to work OK!

So a rebuild of the executable at *https://releases.rancher.com/dapper/latest/* would be appreciated!

**Comment by bjfr** [comment]
Any progress on this issue?

**Comment by ryansch** [comment]
I just hit my head on this as well.

**Comment by ryansch** [comment]
Here's a one liner to build from source if you have docker installed:
```
docker run --rm -v $(pwd):/go/src/github.com/rancher/dapper -w /go/src/github.com/rancher/dapper -e GOOS=darwin golang:latest go build
```

**Comment by dramich** [comment]
This has been resolved in the [latest release](https://github.com/rancher/dapper/releases/latest)
